### ISSUE TITLE
Wrong emblem-important icon in Evolution composer toolbar

### ISSUE THREAD

**Issue by siavashs** [vinceliuice/vimix-icon-theme#10]
I noticed that Evolution composer toolbar shows a wrong `emblem-important` icon which forces the toolbar to expand:
![image](https://user-images.githubusercontent.com/113189/53814058-3da24b00-3f5f-11e9-8162-c5602791b8bf.png)
The source of the icon is [Paper-Vimix/other/emblems/emblem-important.png](https://github.com/vinceliuice/vimix-icon-theme/blob/master/Paper-Vimix/other/emblems/emblem-important.png)

**Comment by vinceliuice** [comment]
Fixed now
