### ISSUE TITLE
Gvim toolbar large icon

### ISSUE THREAD

**Issue by digaev** [vinceliuice/vimix-icon-theme#12]
I'm not sure if the problem is on your side, but take a look https://imgur.com/a/zUUfmpP
I'm on Fedora 30, Gnome 3.32.2.

Thanks.

**Comment by jose-sanchezm** [comment]
The same happens with synaptic:

![image](https://user-images.githubusercontent.com/18676221/58708588-8334af80-83b8-11e9-936a-6cf94d30f473.png)

**Comment by vinceliuice** [comment]
I'll fix this

**Comment by vinceliuice** [comment]
Fixed now
