### ISSUE TITLE
some applications like libreoffice have menu issues

### ISSUE THREAD

**Issue by vishwasks32** [vinceliuice/vimix-icon-theme#13]
libreoffice menu is like this
![Screenshot_2019-09-01_21-57-22](https://user-images.githubusercontent.com/5550783/64079274-320fc100-cd03-11e9-9b57-4b81bc06f8c4.png)
Is this an issue from theme?
How can we fix this?

**Comment by vinceliuice** [comment]
Libreoffice use it's own icon theme, not use user or system icon theme, you can only change it from libre setting
