### ISSUE TITLE
Plus and minus sign misisng after gnome shell 3.36

### ISSUE THREAD

**Issue by ryandward** [vinceliuice/vimix-icon-theme#14]
![image](https://user-images.githubusercontent.com/6970996/76390205-ff422780-633a-11ea-9451-423cd80c7687.png)
For instance, you can see the plus and minus here, have become corrupted somehow. They should be on the bottom right; instead you can see two null icons.

**Comment by vinceliuice** [comment]
![2020-03-11 16-33-54 的屏幕截图](https://user-images.githubusercontent.com/7604295/76398260-892fd600-63b7-11ea-9522-287678ce4ff8.png)

**Comment by vinceliuice** [comment]
Don't get this issue

**Comment by dvorapa** [comment]
Same for me

**Comment by vinceliuice** [comment]
Did you installed from github?  @dvorapa  @ryandward , because I tested on my gnome-shell 3.36, but I don't have this issue

**Comment by dvorapa** [comment]
Yes, from current master

**Comment by vinceliuice** [comment]
I don't know what's going on about this, I just sure everything works fine on my ubuntu gnome-shell 3.36

**Comment by mnabid** [comment]
I'm having issues too....installed today from master. 
**Screenshot 1:**
![Screenshot from 2020-03-13 01-52-04](https://user-images.githubusercontent.com/62117272/76561616-dd2cde80-64cd-11ea-88cb-cfdf76ce2518.png)
**Screenshot 2:**
![Screenshot from 2020-03-13 01-52-15](https://user-images.githubusercontent.com/62117272/76561726-16654e80-64ce-11ea-8f5c-ad18f1a5d696.png)

**Comment by dvorapa** [comment]
Perhaps this is an issue with xorg? (I don't use Wayland)

**Comment by mnabid** [comment]
(symbolic/actions) list-add-symbolic.svg and list-remove-symbolic.svg give the error: 
**XML parse error: error code=201 (3) in (null):5:60: Namespace prefix osb for paint on linearGradient is not defined**

**Comment by vinceliuice** [comment]
I get it now, you system must be fedora, I'll fix this

**Comment by dvorapa** [comment]
> 
> 
> I get it now, you system must be fedora, I'll fix this

No (I'm using Arch), this is rather an issue with the new version of librsvg. Perhaps you still have the old one. Anyway, the same fix has been applied to Paper icon theme this week, so I suppose this fix should do.

**Comment by vinceliuice** [comment]
Thanks @dvorapa , now I know the reason, I'll check all my icon theme and fix this

**Comment by vinceliuice** [comment]
Fixed
