### ISSUE TITLE
Missing - and + icons

### ISSUE THREAD

**Issue by xandora** [vinceliuice/vimix-icon-theme#20]
The - and + icons seem to be missing from the latest release. Current theme installed is Vimix dark (Paper).

![image](https://user-images.githubusercontent.com/2021268/87115371-2435af80-c2c7-11ea-9825-206d0d09f7cb.png)

**Comment by vinceliuice** [comment]
I did not update the release, I'll update a new release

**Comment by xandora** [comment]
Perfect! It's working now.
