### ISSUE TITLE
Volume/Brightness overlays show pixelated icons

### ISSUE THREAD

**Issue by spacepluk** [vinceliuice/vimix-icon-theme#3]
![screenshot from 2018-01-07 10-38-48](https://user-images.githubusercontent.com/824762/34648232-115a6ec0-f397-11e7-9032-6ba68486e322.png)

**Comment by ardichoke** [comment]
The brightness one is even worse too. This definitely has to do with commit 9665998cac6070d10d370f1c46579ad59cddb9eb

Switching all the types to fixed resulted in lower resolution icons being used. This commit should be reverted.

**Comment by vinceliuice** [comment]
I'll fix this
